# [任意] mp4 を出力するフォルダを指定します
# パスの最後にはスラッシュを付けてください
# 未指定または空文字列にした場合この台本ファイルがあるフォルダに出力します
out_dir = ""


# =============== 画面設定 ===============
# [キャラクターを表示する場合必須] 立ち絵のファイルパスと表示座標と縮尺を指定します
# 画像ファイルは各表情の「口閉じ、口開き」の 2 ファイルのリストを指定します
# なければ1ファイルのみのリストでもよいです (が口パクしません)
[[character_images]]
name = "ずんだもん"
coord = [675, 290]
scale = 0.58
faces = [
  ["./materials/zundamon_10.png", "./materials/zundamon_11.png"],  # 表情 0
  ["./materials/zundamon_20.png", "./materials/zundamon_21.png"],  # 表情 1
]
[[character_images]]
name = "春日部つむぎ"
coord = [-27, 275]
scale = 0.555
faces = [
  ["./materials/tsumugi_10.png", "./materials/tsumugi_11.png"],  # 表情 0
  ["./materials/tsumugi_20.png", "./materials/tsumugi_21.png"],  # 表情 1
]

# [字幕を表示する場合必須] 画面に描画するセリフテキスト (字幕) の設定を指定します
[serifu_text_settings]
coord = [167, 345]
font_size = 26
width = 21  # 字幕領域の横幅を文字数で指定してください
spacing = 1  # 改行幅
font_path = "C:\\Windows\\Fonts\\MPLUS2-Black.ttf"
# フォント色を話者ごとに指定してください
font_color = { "ずんだもん" = [153, 213, 102], "春日部つむぎ" = [233, 206, 118] }
font_color_default = [255, 255, 255]  # 1行上で指定されなかった話者のフォント色
stroke_width = 3  # ふちどり幅 (optional)
stroke_fill = "black"  # ふちどり色 (optional)

# [フリーテキストを表示する場合必須] 画面に描画するフリーテキストの設定を指定します
[free_text_settings]
coord = [35, 33]
font_size = 30
font_path = "C:\\Windows\\Fonts\\MPLUS2-Black.ttf"
font_color = [0, 0, 0]
width = 24  # フリーテキスト領域の横幅を文字数で指定してください
spacing = 5  # 改行幅
# ふちどり幅, ふちどり色も任意で指定できます


# =============== 音声設定 ===============
# [任意] VOICEVOX FastAPI の /synthesis に渡すオプションを指定します
# ここではずんだもんの話速を速めて抑揚を抑え、
# またずんだもんもつむぎも音高を落ち着かせています
[[voice_settings]]
speaker_style = "ずんだもん:ノーマル"
options = { speedScale = 1.2, intonationScale = 0.9, pitchScale = -0.025 }
[[voice_settings]]
speaker_style = "春日部つむぎ:ノーマル"
options = { pitchScale = -0.025 }

# [任意] BGM を指定します
[bgm_settings]
mp3_path = ""
adjust = -10  # BGM の音量調整


# =============== 台本 ===============
# [必須] 場面のデフォルト設定を指定します (各場面はこの設定への差分のみ指定します)
[shot_default]
display_serifu = true  # 字幕を表示するか否か
back_size = [854, 480]  # 背景サイズ (画像パス指定時は無視)
back_color = [204, 226, 229]  # 背景色 (画像パス指定時は無視)
characters = { "ずんだもん" = 0, "春日部つむぎ" = 0 }  # 場面の登場人物及びその表情
free_text = "自己共分散関数:\nC(k) = E[(y_{n} - mu)(y_{n-k} - mu)]"  # フリーテキスト
style = "ノーマル"  # 既定の声のスタイル (VOICEVOX のスタイル名を指定)

# [任意] 前景画像を登録します
[front_images]

# [必須] 各場面のセリフや背景画像や表情などを指定していきます
[[shots]]
silence = 1

[[shots]]
speaker = "ずんだもん"
serifu = "定常時系列のあるステップとkステップ前の共分散をラグkの関数と考えて自己共分散関数というのだ。"

[[shots]]
speaker = "春日部つむぎ"
serifu = "定常時系列じゃないとだめなのー？"

[[shots]]
speaker = "ずんだもん"
serifu = "時系列が定常でない場合自己共分散はラグkのみでは決まらないのだ。時間ステップによって変わっていってしまうかもしれないのだ。"
free_text = "自己共分散関数:\nC(k) = E[(y_{n} - mu)(y_{n-k} - mu)]\n\n定常時系列:\n平均と分散が時刻に依存しない\n自己共分散が時刻に依存せずラグのみに依存する"

[[shots]]
speaker = "春日部つむぎ"
serifu = "あーそっかー。"
free_text = "自己共分散関数:\nC(k) = E[(y_{n} - mu)(y_{n-k} - mu)]\n\n定常時系列:\n平均と分散が時刻に依存しない\n自己共分散が時刻に依存せずラグのみに依存する"

[[shots]]
silence = 5
characters = { "ずんだもん" = 1, "春日部つむぎ" = 1 }
free_text = "[声の出演]\nVOICEVOX:ずんだもん\nVOICEVOX:春日部つむぎ"
